language: php
sudo: true
dist: trusty
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

addons:
  postgresql: "9.3"

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm" ]]; then source ./.setup/travis/hhvm.sh; fi
  - ./.setup/travis.sh
  - psql -c 'create database test_hwgrading;' -U postgres
  - psql --host=localhost --username=postgres --command="CREATE GROUP test_hwgrading ROLE postgres"
  - psql -f TAGradingServer/data/tables.sql -U postgres -d test_hwgrading
  - psql -f TAGradingServer/data/inserts.sql -U postgres -d test_hwgrading
  - psql -f tests/testData/travis.sql -U postgres -d test_hwgrading

script:
  - phpunit --version
  - phpunit --configuration tests/phpunit.xml
  - find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

notifications:
  email: false