language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    
addons:
  postgresql: "9.3"
  
before_script:
  - psql -c 'create database test_hwgrading;' -U postgres
  - psql --host=localhost --username=postgres --command="CREATE GROUP test_hwgrading ROLE postgres"
  - psql -f tests/TAGradingServer/travis.sql -U postgres -d test_hwgrading
  
script: 
  - phpunit tests/controller/*
  - phpunit --configuration tests/TAGradingServer/phpunit.xml
  - find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l

notifications:
  email: false