name: Submitty CI-2

on push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.6'
      - name: Cache Pip
        uses: actions/cache@v2
        with:
          path: path ~/.cache/pip
          key: ${{ runner.os }}-py-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py-pip
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install python-pam
          python3 -m pip install sqlalchemy
          python3 -m pip install selenium
          python3 -m pip install tzlocal
          python3 -m pip install jsonschema
          python3 -m pip install jsonref
          python3 -m pip install docker
          python3 -m pip install websocket_client
      - name: Setup Submitty
        run: |
          pwd
          ls 